export const countryData = [
  {
    id: 1,
    flag: "/country/canadaflag.jpg",
    bg: "/places/canada.jpg",
    name: "Canada",
  },
  { id: 2, flag: "/country/flaguk.jpg", bg: "/places/uk.jpg", name: "UK" },
  {
    id: 3,
    flag: "/country/flagaustralia.jpg",
    bg: "/places/aus.jpg",
    name: "Australia",
  },
  {
    id: 4,
    flag: "/country/flagnewzealand.jpg",
    bg: "/places/nz.jpg",
    name: "New Zealand",
  },
  {
    id: 5,
    flag: "/country/flagGermany.jpg",
    bg: "/places/ger.jpg",
    name: "Germany",
  },
  {
    id: 6,
    flag: "/country/flagus.jpg",
    bg: "/places/us.jpg",
    name: "United States",
  },
  {
    id: 7,
    flag: "/country/flagBulgeria.jpg",
    bg: "/places/bulg.jpg",
    name: "Bulgaria",
  },
  {
    id: 8,
    flag: "/country/flagDenmark.jpg",
    bg: "/places/den.jpg",
    name: "Denmark",
  },
  {
    id: 9,
    flag: "/country/flagFrance.jpg",
    bg: "/places/fra.jpg",
    name: "France",
  },
  {
    id: 10,
    flag: "/country/flagireland.jpg",
    bg: "/places/ire.jpg",
    name: "Ireland",
  },
  {
    id: 11,
    flag: "/country/flagItaly.jpg",
    bg: "/places/ita.jpg",
    name: "Italy",
  },
  {
    id: 12,
    flag: "/country/flagmalaysia.jpg",
    bg: "/places/mala.jpg",
    name: "Malaysia",
  },
  {
    id: 13,
    flag: "/country/flagnetherlands.png",
    bg: "/places/neth.jpg",
    name: "Netherland",
  },
  {
    id: 14,
    flag: "/country/flagrussia.jpg",
    bg: "/places/russ.jpg",
    name: "Russia",
  },
  {
    id: 15,
    flag: "/country/flagkorea.jpg",
    bg: "/places/sk.jpg",
    name: "South Korea",
  },
  {
    id: 16,
    flag: "/country/flagSweden.jpg",
    bg: "/places/swe.jpg",
    name: "Sweden",
  },
  {
    id: 17,
    flag: "/country/flagSwis.png",
    bg: "/places/swi.jpg",
    name: "Switzerland",
  },
];
