export const candidatesList = [
  {
    id: 1,
    fullname: "Gabriell Collough",
    jobrole: "Compensation Analyst",
    email: "gcollough0@devhub.com",
    gender: "Female",
    location: "Portugal",
    expectedCTC: 36.7,
    currentCTC: 12.5,
    createdAt: "1/21/2024",
    age: 27,
    experience: "1-2",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Masters Degree",
    image: "/user-1.png",
  },
  {
    id: 2,
    fullname: "Esma Haswall",
    jobrole: "Financial Advisor",
    email: "ehaswall1@blogs.com",
    gender: "Female",
    location: "Indonesia",
    expectedCTC: 13.6,
    currentCTC: 13.3,
    createdAt: "7/27/2023",
    age: 34,
    experience: "fresher",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Certificate",
    image: "/user-4.png",
  },
  {
    id: 3,
    fullname: "Gallard Kilbride",
    jobrole: "Cost Accountant",
    email: "gkilbride2@hibu.com",
    gender: "Male",
    location: "Mongolia",
    expectedCTC: 31.5,
    currentCTC: 23.0,
    createdAt: "8/8/2023",
    age: 25,
    experience: "2-4",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Masters Degree",
    image: "/user-3.png",
  },
  {
    id: 4,
    fullname: "Wake Gaitskill",
    jobrole: "Executive Secretary",
    email: "wgaitskill3@liveinternet.ru",
    gender: "Male",
    location: "Philippines",
    expectedCTC: 25.6,
    currentCTC: 39.9,
    createdAt: "5/1/2024",
    age: 37,
    experience: ">6",
    language: "English German Spanish",
    highestEducation: "Bachelors Degree",
    image: "/user-1.png",
  },
  {
    id: 5,
    fullname: "Dorothea Drought",
    jobrole: "Product Engineer",
    email: "ddrought4@comsenz.com",
    gender: "Female",
    location: "Portugal",
    expectedCTC: 5.0,
    currentCTC: 21.8,
    createdAt: "6/27/2023",
    age: 18,
    experience: "1-2",
    language: "English Hindi Malayalam",
    highestEducation: "Doctorate",
    image: "/user-1.png",
  },
  {
    id: 6,
    fullname: "Guinevere Fairham",
    jobrole: "Budget/Accounting Analyst IV",
    email: "gfairham5@imgur.com",
    gender: "Female",
    location: "China",
    expectedCTC: 8.3,
    currentCTC: 31.8,
    createdAt: "7/21/2023",
    age: 34,
    experience: "4-6",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Certificate",
    image: "/user-1.png",
  },
  {
    id: 7,
    fullname: "Cliff Neem",
    jobrole: "Senior Cost Accountant",
    email: "cneem6@t.co",
    gender: "Male",
    location: "Tunisia",
    expectedCTC: 6.7,
    currentCTC: 26.7,
    createdAt: "2/14/2024",
    age: 39,
    experience: "1-2",
    language: "English German Spanish",
    highestEducation: "Masters Degree",
    image: "/user-4.png",
  },
  {
    id: 8,
    fullname: "Burt Ambrogioni",
    jobrole: "Food Chemist",
    email: "bambrogioni7@woothemes.com",
    gender: "Male",
    location: "Russia",
    expectedCTC: 5.3,
    currentCTC: 10.4,
    createdAt: "8/14/2023",
    age: 18,
    experience: "fresher",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Bachelors Degree",
    image: "/user-1.png",
  },
  {
    id: 9,
    fullname: "Xever Mongain",
    jobrole: "Health Coach II",
    email: "xmongain8@cyberchimps.com",
    gender: "Polygender",
    location: "Azerbaijan",
    expectedCTC: 14.7,
    currentCTC: 31.9,
    createdAt: "11/16/2023",
    age: 39,
    experience: "4-6",
    language: "English German Spanish",
    highestEducation: "Masters Degree",
    image: "/user-3.png",
  },
  {
    id: 10,
    fullname: "Giffer Caldecourt",
    jobrole: "Technical Writer",
    email: "gcaldecourt9@lulu.com",
    gender: "Male",
    location: "Brazil",
    expectedCTC: 16.8,
    currentCTC: 25.8,
    createdAt: "3/22/2024",
    age: 18,
    experience: "fresher",
    language: "English Hindi Malayalam",
    highestEducation: "Masters Degree",
    image: "/user-4.png",
  },
  {
    id: 11,
    fullname: "Cate Bunclark",
    jobrole: "Geological Engineer",
    email: "cbunclarka@weibo.com",
    gender: "Female",
    location: "Honduras",
    expectedCTC: 24.9,
    currentCTC: 31.0,
    createdAt: "6/10/2024",
    age: 29,
    experience: "4-6",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Doctorate",
    image: "/user-2.png",
  },
  {
    id: 12,
    fullname: "Egbert Battson",
    jobrole: "Staff Scientist",
    email: "ebattsonb@ovh.net",
    gender: "Male",
    location: "China",
    expectedCTC: 21.9,
    currentCTC: 24.6,
    createdAt: "6/14/2024",
    age: 32,
    experience: ">6",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Doctorate",
    image: "/user-2.png",
  },
  {
    id: 13,
    fullname: "Fred Rickersey",
    jobrole: "Structural Engineer",
    email: "frickerseyc@umich.edu",
    gender: "Polygender",
    location: "Peru",
    expectedCTC: 7.8,
    currentCTC: 26.2,
    createdAt: "12/28/2023",
    age: 35,
    experience: "fresher",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Bachelors Degree",
    image: "/user-2.png",
  },
  {
    id: 14,
    fullname: "Jacinda Frankel",
    jobrole: "Community Outreach Specialist",
    email: "jfrankeld@storify.com",
    gender: "Female",
    location: "Brazil",
    expectedCTC: 29.2,
    currentCTC: 31.9,
    createdAt: "5/28/2024",
    age: 31,
    experience: "2-4",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Bachelors Degree",
    image: "/user-2.png",
  },
  {
    id: 15,
    fullname: "Karlee Rawls",
    jobrole: "Junior Executive",
    email: "krawlse@slate.com",
    gender: "Female",
    location: "Indonesia",
    expectedCTC: 33.1,
    currentCTC: 6.2,
    createdAt: "7/2/2023",
    age: 35,
    experience: "2-4",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Diploma",
    image: "/user-4.png",
  },
  {
    id: 16,
    fullname: "Daphna Gwynn",
    jobrole: "Database Administrator II",
    email: "dgwynnf@foxnews.com",
    gender: "Female",
    location: "Ukraine",
    expectedCTC: 2.1,
    currentCTC: 36.1,
    createdAt: "11/22/2023",
    age: 36,
    experience: ">6",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Doctorate",
    image: "/user-3.png",
  },
  {
    id: 17,
    fullname: "Moses Devigne",
    jobrole: "Safety Technician II",
    email: "mdevigneg@pcworld.com",
    gender: "Male",
    location: "United States",
    expectedCTC: 2.9,
    currentCTC: 39.2,
    createdAt: "7/23/2023",
    age: 23,
    experience: "fresher",
    language: "English German Spanish",
    highestEducation: "Certificate",
    image: "/user-3.png",
  },
  {
    id: 18,
    fullname: "Hildagarde Andrick",
    jobrole: "Tax Accountant",
    email: "handrickh@reddit.com",
    gender: "Female",
    location: "France",
    expectedCTC: 18.0,
    currentCTC: 26.2,
    createdAt: "12/28/2023",
    age: 32,
    experience: ">6",
    language: "English German Spanish",
    highestEducation: "Diploma",
    image: "/user-1.png",
  },
  {
    id: 19,
    fullname: "Ignatius Rebichon",
    jobrole: "Help Desk Operator",
    email: "irebichoni@technorati.com",
    gender: "Male",
    location: "Sweden",
    expectedCTC: 10.4,
    currentCTC: 25.4,
    createdAt: "11/2/2023",
    age: 18,
    experience: "4-6",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Bachelors Degree",
    image: "/user-3.png",
  },
  {
    id: 20,
    fullname: "Ronalda Kunzler",
    jobrole: "Account Representative IV",
    email: "rkunzlerj@quantcast.com",
    gender: "Female",
    location: "Venezuela",
    expectedCTC: 3.9,
    currentCTC: 37.9,
    createdAt: "9/11/2023",
    age: 32,
    experience: "4-6",
    language: "English Hindi Malayalam",
    highestEducation: "Bachelors Degree",
    image: "/user-1.png",
  },
  {
    id: 21,
    fullname: "Roberta Hehl",
    jobrole: "Marketing Manager",
    email: "rhehlk@icio.us",
    gender: "Female",
    location: "Indonesia",
    expectedCTC: 14.3,
    currentCTC: 21.2,
    createdAt: "1/9/2024",
    age: 21,
    experience: "1-2",
    language: "English Hindi Malayalam",
    highestEducation: "Doctorate",
    image: "/user-1.png",
  },
  {
    id: 22,
    fullname: "Antone Luquet",
    jobrole: "Software Test Engineer III",
    email: "aluquetl@usda.gov",
    gender: "Male",
    location: "China",
    expectedCTC: 25.7,
    currentCTC: 35.0,
    createdAt: "5/20/2024",
    age: 32,
    experience: "1-2",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Certificate",
    image: "/user-3.png",
  },
  {
    id: 23,
    fullname: "Coral Wildin",
    jobrole: "Environmental Tech",
    email: "cwildinm@toplist.cz",
    gender: "Female",
    location: "Taiwan",
    expectedCTC: 36.3,
    currentCTC: 21.8,
    createdAt: "3/21/2024",
    age: 26,
    experience: ">6",
    language: "English German Spanish",
    highestEducation: "Masters Degree",
    image: "/user-1.png",
  },
  {
    id: 24,
    fullname: "Boothe Iwanowski",
    jobrole: "Social Worker",
    email: "biwanowskin@nasa.gov",
    gender: "Male",
    location: "Togo",
    expectedCTC: 31.5,
    currentCTC: 32.6,
    createdAt: "4/23/2024",
    age: 34,
    experience: ">6",
    language: "English German Spanish",
    highestEducation: "Doctorate",
    image: "/user-2.png",
  },
  {
    id: 25,
    fullname: "Jobi Francklyn",
    jobrole: "Data Coordinator",
    email: "jfrancklyno@facebook.com",
    gender: "Female",
    location: "Indonesia",
    expectedCTC: 14.4,
    currentCTC: 24.7,
    createdAt: "1/27/2024",
    age: 37,
    experience: "2-4",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Diploma",
    image: "/user-3.png",
  },
  {
    id: 26,
    fullname: "Jeana Kilius",
    jobrole: "Graphic Designer",
    email: "jkiliusp@mapy.cz",
    gender: "Female",
    location: "Palestinian Territory",
    expectedCTC: 10.8,
    currentCTC: 14.8,
    createdAt: "4/6/2024",
    age: 26,
    experience: ">6",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Bachelors Degree",
    image: "/user-2.png",
  },
  {
    id: 27,
    fullname: "Ignaz Megany",
    jobrole: "Professor",
    email: "imeganyq@bigcartel.com",
    gender: "Male",
    location: "Ukraine",
    expectedCTC: 21.4,
    currentCTC: 15.2,
    createdAt: "6/14/2024",
    age: 19,
    experience: ">6",
    language: "English Hindi Malayalam",
    highestEducation: "Doctorate",
    image: "/user-3.png",
  },
  {
    id: 28,
    fullname: "Batsheva Picheford",
    jobrole: "Paralegal",
    email: "bpichefordr@w3.org",
    gender: "Female",
    location: "Russia",
    expectedCTC: 39.8,
    currentCTC: 14.6,
    createdAt: "8/19/2023",
    age: 31,
    experience: "1-2",
    language: "English Hindi Malayalam",
    highestEducation: "Masters Degree",
    image: "/user-3.png",
  },
  {
    id: 29,
    fullname: "Tiffy Irdale",
    jobrole: "Actuary",
    email: "tirdales@artisteer.com",
    gender: "Female",
    location: "China",
    expectedCTC: 17.5,
    currentCTC: 28.4,
    createdAt: "7/31/2023",
    age: 19,
    experience: "fresher",
    language: "English Spanish Arabic Hindi",
    highestEducation: "Masters Degree",
    image: "/user-2.png",
  },
  {
    id: 30,
    fullname: "Kalli Dike",
    jobrole: "Biostatistician IV",
    email: "kdiket@behance.net",
    gender: "Female",
    location: "Malta",
    expectedCTC: 23.3,
    currentCTC: 7.2,
    createdAt: "12/24/2023",
    age: 34,
    experience: ">6",
    language: "English German Spanish",
    highestEducation: "Bachelors Degree",
    image: "/user-3.png",
  },
];
