export const companyList = [
  {
    id: 1,
    company: "Zoomzone",
    category: "Health & Care",
    email: "cfosdike0@foxnews.com",
    phone: "673-133-8779",
    location: "Colombia",
    size: ">800",
    openJobs: 1,
    founded: 2012,
    image: "/company-3.png",
    website: "https://icq.com",
  },
  {
    id: 2,
    company: "Fanoodle",
    category: "Development",
    email: "bruncieman1@feedburner.com",
    phone: "839-628-6051",
    location: "Mexico",
    size: "200-400",
    openJobs: 37,
    founded: 2009,
    image: "/company-4.png",
    website: "http://marriott.com",
  },
  {
    id: 3,
    company: "Mydeo",
    category: "Design",
    email: "rizhakov2@wiley.com",
    phone: "761-632-8557",
    location: "Portugal",
    size: ">800",
    openJobs: 28,
    founded: 2007,
    image: "/company-3.png",
    website: "http://xrea.com",
  },
  {
    id: 4,
    company: "Tagcat",
    category: "Health & Care",
    email: "jledram3@nature.com",
    phone: "211-465-3580",
    location: "Afghanistan",
    size: "50-100",
    openJobs: 26,
    founded: 1998,
    image: "/company-4.png",
    website: "https://mtv.com",
  },
  {
    id: 5,
    company: "Linklinks",
    category: "Accounting/Finance",
    email: "maltoft4@deviantart.com",
    phone: "987-136-9995",
    location: "Poland",
    size: ">800",
    openJobs: 12,
    founded: 2011,
    image: "/company-2.png",
    website: "http://jalbum.net",
  },
  {
    id: 6,
    company: "Zoonoodle",
    category: "Automotive Jobs",
    email: "tmuirden5@google.nl",
    phone: "478-895-5075",
    location: "Poland",
    size: ">800",
    openJobs: 1,
    founded: 1999,
    image: "/company-4.png",
    website: "http://house.gov",
  },
  {
    id: 7,
    company: "Aivee",
    category: "Automotive Jobs",
    email: "dkynson6@jimdo.com",
    phone: "452-917-7198",
    location: "China",
    size: ">800",
    openJobs: 38,
    founded: 2004,
    image: "/company-2.png",
    website: "http://census.gov",
  },
  {
    id: 8,
    company: "Vidoo",
    category: "Customer Service",
    email: "afrushard7@senate.gov",
    phone: "494-152-3127",
    location: "United Kingdom",
    size: "100-200",
    openJobs: 29,
    founded: 1992,
    image: "/company-1.png",
    website: "https://ox.ac.uk",
  },
  {
    id: 9,
    company: "Zooxo",
    category: "Marketing",
    email: "jfolker8@reddit.com",
    phone: "614-648-1440",
    location: "Tunisia",
    size: "200-400",
    openJobs: 6,
    founded: 1998,
    image: "/company-4.png",
    website: "https://google.fr",
  },
  {
    id: 10,
    company: "Oyope",
    category: "Human Resource",
    email: "kcrates9@tripod.com",
    phone: "471-956-4740",
    location: "Belarus",
    size: "10-50",
    openJobs: 15,
    founded: 2006,
    image: "/company-2.png",
    website: "https://princeton.edu",
  },
  {
    id: 11,
    company: "Zoombox",
    category: "Accounting/Finance",
    email: "tbarukha@stanford.edu",
    phone: "432-904-0187",
    location: "Brazil",
    size: "50-100",
    openJobs: 16,
    founded: 1998,
    image: "/company-1.png",
    website: "https://accuweather.com",
  },
  {
    id: 12,
    company: "Zava",
    category: "Design",
    email: "dbaggelleyb@goo.ne.jp",
    phone: "922-194-0332",
    location: "Denmark",
    size: ">800",
    openJobs: 11,
    founded: 1985,
    image: "/company-1.png",
    website: "https://infoseek.co.jp",
  },
  {
    id: 13,
    company: "Yadel",
    category: "Design",
    email: "sissonc@yandex.ru",
    phone: "175-833-7195",
    location: "Vietnam",
    size: "100-200",
    openJobs: 12,
    founded: 1986,
    image: "/company-4.png",
    website: "https://unicef.org",
  },
  {
    id: 14,
    company: "Ailane",
    category: "Development",
    email: "cblackstockd@unc.edu",
    phone: "244-470-9598",
    location: "Philippines",
    size: "200-400",
    openJobs: 6,
    founded: 2006,
    image: "/company-4.png",
    website: "http://fema.gov",
  },
  {
    id: 15,
    company: "Oyoba",
    category: "Customer Service",
    email: "nheele@bloglovin.com",
    phone: "860-842-4680",
    location: "Tanzania",
    size: ">800",
    openJobs: 6,
    founded: 2002,
    image: "/company-4.png",
    website: "https://marketwatch.com",
  },
  {
    id: 16,
    company: "Pixonyx",
    category: "Automotive Jobs",
    email: "chugonneauf@vkontakte.ru",
    phone: "993-304-0484",
    location: "Indonesia",
    size: "400-800",
    openJobs: 29,
    founded: 1995,
    image: "/company-1.png",
    website: "https://fotki.com",
  },
  {
    id: 17,
    company: "Tagcat",
    category: "Accounting/Finance",
    email: "adeliag@addthis.com",
    phone: "135-157-5155",
    location: "Micronesia",
    size: "10-50",
    openJobs: 35,
    founded: 2005,
    image: "/company-4.png",
    website: "http://jimdo.com",
  },
  {
    id: 18,
    company: "Meemm",
    category: "Automotive Jobs",
    email: "bruddomh@patch.com",
    phone: "971-307-0560",
    location: "Peru",
    size: ">800",
    openJobs: 30,
    founded: 2002,
    image: "/company-3.png",
    website: "http://abc.net.au",
  },
  {
    id: 19,
    company: "Brainbox",
    category: "Human Resource",
    email: "tgashi@123-reg.co.uk",
    phone: "535-623-7086",
    location: "Panama",
    size: "200-400",
    openJobs: 18,
    founded: 1999,
    image: "/company-1.png",
    website: "https://about.com",
  },
  {
    id: 20,
    company: "Podcat",
    category: "Health & Care",
    email: "vtestroj@springer.com",
    phone: "178-323-3871",
    location: "Portugal",
    size: "10-50",
    openJobs: 14,
    founded: 2012,
    image: "/company-2.png",
    website: "https://rediff.com",
  },
  {
    id: 21,
    company: "Youopia",
    category: "Development",
    email: "acardnok@loc.gov",
    phone: "808-637-3810",
    location: "Finland",
    size: ">800",
    openJobs: 29,
    founded: 1995,
    image: "/company-3.png",
    website: "http://nba.com",
  },
  {
    id: 22,
    company: "Meemm",
    category: "Marketing",
    email: "npontainl@pinterest.com",
    phone: "725-435-0477",
    location: "Indonesia",
    size: "50-100",
    openJobs: 6,
    founded: 2002,
    image: "/company-1.png",
    website: "http://unesco.org",
  },
  {
    id: 23,
    company: "Ntags",
    category: "Accounting/Finance",
    email: "bquartermainm@indiatimes.com",
    phone: "277-915-8920",
    location: "Poland",
    size: "200-400",
    openJobs: 35,
    founded: 1971,
    image: "/company-2.png",
    website: "http://fda.gov",
  },
  {
    id: 24,
    company: "Izio",
    category: "Development",
    email: "shanhamn@npr.org",
    phone: "370-401-1675",
    location: "Indonesia",
    size: "10-50",
    openJobs: 7,
    founded: 1993,
    image: "/company-1.png",
    website: "https://sogou.com",
  },
  {
    id: 25,
    company: "Riffpedia",
    category: "Development",
    email: "rcrosstono@wix.com",
    phone: "857-421-4768",
    location: "Canada",
    size: "100-200",
    openJobs: 12,
    founded: 2002,
    image: "/company-2.png",
    website: "https://mapquest.com",
  },
  {
    id: 26,
    company: "Oodoo",
    category: "Design",
    email: "csutheringtonp@bravesites.com",
    phone: "512-403-8990",
    location: "United States",
    size: "100-200",
    openJobs: 39,
    founded: 1993,
    image: "/company-1.png",
    website: "http://netscape.com",
  },
  {
    id: 27,
    company: "Voonte",
    category: "Human Resource",
    email: "nwardq@google.co.jp",
    phone: "895-983-6167",
    location: "China",
    size: ">800",
    openJobs: 23,
    founded: 1988,
    image: "/company-3.png",
    website: "http://tiny.cc",
  },
  {
    id: 28,
    company: "Jabbersphere",
    category: "Marketing",
    email: "rtottemr@virginia.edu",
    phone: "784-637-2688",
    location: "Iran",
    size: "50-100",
    openJobs: 27,
    founded: 1999,
    image: "/company-1.png",
    website: "https://acquirethisname.com",
  },
  {
    id: 29,
    company: "Voonyx",
    category: "Health & Care",
    email: "tblankets@wiley.com",
    phone: "882-490-2816",
    location: "China",
    size: "400-800",
    openJobs: 28,
    founded: 1997,
    image: "/company-2.png",
    website: "https://privacy.gov.au",
  },
  {
    id: 30,
    company: "Quaxo",
    category: "Human Resource",
    email: "wfearnsidet@answers.com",
    phone: "400-536-7024",
    location: "Indonesia",
    size: "10-50",
    openJobs: 33,
    founded: 2000,
    image: "/company-3.png",
    website: "http://dailymail.co.uk",
  },
];
