export const JobDetailsData = [
  {
    id: 1,
    position: "Senior Cost Accountant",
    createdAt: "12/11/2023",
    description: "Physeal fracture of lower end of ulna",
    skills: "DSO",
    applied: 22,
    selected: 18,
    jobType: "Part-Time",
    salary: 6.1,
    company: "Pixonyx",
    status: "recruiting",
    location: "8 Reindahl Plaza",
  },
  {
    id: 2,
    position: "Analyst Programmer",
    createdAt: "27/09/2023",
    description: "Injury of right uterine vein, subsequent encounter",
    skills: "IHT",
    applied: 77,
    selected: 73,
    jobType: "Full-Time",
    salary: 13.8,
    company: "Divavu",
    status: "recruiting",
    location: "9 Judy Terrace",
  },
  {
    id: 3,
    position: "Programmer Analyst I",
    createdAt: "26/02/2024",
    description: "Epidural hemorrhage w LOC of unsp duration, sequela",
    skills: "Glasses",
    applied: 30,
    selected: 89,
    jobType: "Part-Time",
    salary: 7.3,
    company: "Ntags",
    status: "expired",
    location: "1 Prairie Rose Plaza",
  },
  {
    id: 4,
    position: "Data Coordinator",
    createdAt: "06/06/2024",
    description: "Acute ethmoidal sinusitis, unspecified",
    skills: "RQM",
    applied: 71,
    selected: 53,
    jobType: "Internship",
    salary: 16.0,
    company: "Jetwire",
    status: "expired",
    location: "29364 Ronald Regan Terrace",
  },
  {
    id: 5,
    position: "Speech Pathologist",
    createdAt: "19/12/2023",
    description: "Other specified sprain of right wrist, sequela",
    skills: "RSA Tokens",
    applied: 93,
    selected: 54,
    jobType: "Full-Time",
    salary: 4.8,
    company: "Fiveclub",
    status: "expired",
    location: "88020 Fisk Point",
  },
  {
    id: 6,
    position: "Community Outreach Specialist",
    createdAt: "22/02/2024",
    description: "Malignant neoplasm of other specified ill-defined sites",
    skills: "PK",
    applied: 70,
    selected: 43,
    jobType: "Part-Time",
    salary: 2.2,
    company: "Ntag",
    status: "recruiting",
    location: "0 Northfield Plaza",
  },
  {
    id: 7,
    position: "Associate Professor",
    createdAt: "07/02/2024",
    description: "Other situational type phobia",
    skills: "Glazing",
    applied: 93,
    selected: 76,
    jobType: "Full-Time",
    salary: 13.7,
    company: "Digitube",
    status: "recruiting",
    location: "6 Hanover Hill",
  },
  {
    id: 8,
    position: "Tax Accountant",
    createdAt: "13/08/2023",
    description: "Subluxation of L1/L2 lumbar vertebra, subsequent encounter",
    skills: "Low Voltage",
    applied: 14,
    selected: 18,
    jobType: "Full-Time",
    salary: 16.9,
    company: "Mymm",
    status: "recruiting",
    location: "46 Lakewood Trail",
  },
  {
    id: 9,
    position: "Environmental Tech",
    createdAt: "29/11/2023",
    description: "Tuberculosis of intrathoracic lymph nodes",
    skills: "Hydraulic Fracturing",
    applied: 27,
    selected: 83,
    jobType: "Internship",
    salary: 11.2,
    company: "Quimba",
    status: "expired",
    location: "92 Fordem Park",
  },
  {
    id: 10,
    position: "Senior Editor",
    createdAt: "07/09/2023",
    description: "Acute leukemia of unspecified cell type, in relapse",
    skills: "Dump Truck",
    applied: 61,
    selected: 98,
    jobType: "Internship",
    salary: 12.3,
    company: "Demimbu",
    status: "expired",
    location: "1 2nd Pass",
  },
];

export const description = {
  desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis purus lacus, et cursus elit semper at. Vestibulum cursus molestie erat, id pretium augue. Nulla eget justo vel ipsum faucibus fermentum non vel diam. Donec est tellus, porta nec velit nec, rhoncus interdum mi. Quisque ut ornare leo, ut laoreet erat. Vivamus metus massa, faucibus ac varius quis, facilisis ut nisl. Curabitur sodales vestibulum erat sed laoreet. Nulla facilisi. Cras placerat ullamcorper risus vitae finibus. Vestibulum quis dictum quam. Etiam purus ex, interdum vitae turpis ullamcorper, malesuada commodo risus. Pellentesque quis maximus metus. Sed consequat, purus cursus cursus tincidunt, dolor quam viverra arcu, vitae egestas ex ante a nibh. Sed urna nisl, vestibulum a nunc eget, vehicula luctus ipsum Sed rutrum mi feugiat purus faucibus, vitae venenatis lorem maximus. Fusce vel malesuada tortor. Integer varius lectus id vulputate sollicitudin. Morbi et felis aliquam, pellentesque urna sit amet, aliquet nunc. Nullam rhoncus commodo congue. Pellentesque non libero felis. Vivamus pulvinar neque non libero dapibus, non pulvinar erat dignissim. Fusce dapibus consequat pretium.",
};
