export const jobData = [
  {
    id: 1,
    jobTitle: "Clinical Specialist",
    category: "Human Resources & Recruitment",
    jobtype: "Internship",
    qualification: "Bachelors Degree",
    experience: "0-1",
    gender: "All",
    deadline: "22/06/2025",
    jobLocation: "Remote",
    salary: 9.2,
    location: "Philippines",
    applied: 69,
    isActive: false,
    image: "/company-1.png",
    company: "Jetpulse",
  },
  {
    id: 2,
    jobTitle: "Business Systems Development Analyst",
    category: "Marketing & Advertising",
    jobtype: "Part-time",
    qualification: "Doctorate",
    experience: "fresher",
    gender: "All",
    deadline: "31/12/2024",
    jobLocation: "Remote",
    salary: 26.5,
    location: "Colombia",
    applied: 100,
    isActive: true,
    image: "/company-1.png",
    company: "Dazzlesphere",
  },
  {
    id: 3,
    jobTitle: "Compensation Analyst",
    category: "Customer Service & Support",
    jobtype: "Internship",
    qualification: "Masters Degree",
    experience: "2-4",
    gender: "Female",
    deadline: "15/06/2025",
    jobLocation: "W-F-H",
    salary: 20.0,
    location: "China",
    applied: 23,
    isActive: true,
    image: "/company-2.png",
    company: "Photobug",
  },
  {
    id: 4,
    jobTitle: "Pharmacist",
    category: "Healthcare & Medical",
    jobtype: "Internship",
    qualification: "Diploma",
    experience: "0-1",
    gender: "Male",
    deadline: "07/02/2025",
    jobLocation: "hybrid",
    salary: 37.7,
    location: "Colombia",
    applied: 7,
    isActive: false,
    image: "/company-4.png",
    company: "Linktype",
  },
  {
    id: 5,
    jobTitle: "Executive Secretary",
    category: "Sales",
    jobtype: "Internship",
    qualification: "Certificate",
    experience: "fresher",
    gender: "Male",
    deadline: "23/05/2025",
    jobLocation: "hybrid",
    salary: 23.5,
    location: "Russia",
    applied: 13,
    isActive: true,
    image: "/company-2.png",
    company: "Centimia",
  },
  {
    id: 6,
    jobTitle: "VP Marketing",
    category: "Engineering & Technical",
    jobtype: "Internship",
    qualification: "Certificate",
    experience: "1-2",
    gender: "Male",
    deadline: "21/03/2025",
    jobLocation: "hybrid",
    salary: 21.6,
    location: "Sweden",
    applied: 80,
    isActive: false,
    image: "/company-4.png",
    company: "Brainsphere",
  },
  {
    id: 7,
    jobTitle: "Human Resources Manager",
    category: "Human Resources & Recruitment",
    jobtype: "Full-time",
    qualification: "Bachelors Degree",
    experience: "fresher",
    gender: "Female",
    deadline: "15/02/2025",
    jobLocation: "W-F-H",
    salary: 7.4,
    location: "China",
    applied: 45,
    isActive: false,
    image: "/company-2.png",
    company: "Wordtune",
  },
  {
    id: 8,
    jobTitle: "Staff Scientist",
    category: "Healthcare & Medical",
    jobtype: "Part-time",
    qualification: "Diploma",
    experience: "2-4",
    gender: "Male",
    deadline: "09/04/2025",
    jobLocation: "Remote",
    salary: 32.0,
    location: "Iran",
    applied: 96,
    isActive: false,
    image: "/company-2.png",
    company: "Bubblebox",
  },
  {
    id: 9,
    jobTitle: "Teacher",
    category: "Human Resources & Recruitment",
    jobtype: "Internship",
    qualification: "Certificate",
    experience: ">6",
    gender: "Female",
    deadline: "09/10/2024",
    jobLocation: "W-F-H",
    salary: 34.3,
    location: "Germany",
    applied: 67,
    isActive: true,
    image: "/company-3.png",
    company: "Gevee",
  },
  {
    id: 10,
    jobTitle: "Safety Technician IV",
    category: "Construction & Skilled Trades",
    jobtype: "Part-time",
    qualification: "Doctorate",
    experience: "1-2",
    gender: "All",
    deadline: "26/11/2024",
    jobLocation: "On-site",
    salary: 21.9,
    location: "United States",
    applied: 69,
    isActive: true,
    image: "/company-2.png",
    company: "Bluejam",
  },
  {
    id: 11,
    jobTitle: "Financial Advisor",
    category: "Human Resources & Recruitment",
    jobtype: "Full-time",
    qualification: "Diploma",
    experience: "1-2",
    gender: "Female",
    deadline: "14/12/2024",
    jobLocation: "W-F-H",
    salary: 35.8,
    location: "Croatia",
    applied: 82,
    isActive: true,
    image: "/company-3.png",
    company: "Cogidoo",
  },
  {
    id: 12,
    jobTitle: "Sales Associate",
    category: "Engineering & Technical",
    jobtype: "Internship",
    qualification: "Bachelors Degree",
    experience: "0-1",
    gender: "Female",
    deadline: "01/11/2024",
    jobLocation: "Remote",
    salary: 27.6,
    location: "Indonesia",
    applied: 33,
    isActive: false,
    image: "/company-4.png",
    company: "Skyba",
  },
  {
    id: 13,
    jobTitle: "Senior Financial Analyst",
    category: "Education & Training",
    jobtype: "Part-time",
    qualification: "Bachelors Degree",
    experience: ">6",
    gender: "All",
    deadline: "17/03/2025",
    jobLocation: "hybrid",
    salary: 39.9,
    location: "France",
    applied: 0,
    isActive: false,
    image: "/company-2.png",
    company: "Babbleblab",
  },
  {
    id: 14,
    jobTitle: "Quality Engineer",
    category: "Sales",
    jobtype: "Part-time",
    qualification: "Bachelors Degree",
    experience: "2-4",
    gender: "Male",
    deadline: "26/10/2024",
    jobLocation: "hybrid",
    salary: 13.9,
    location: "China",
    applied: 32,
    isActive: true,
    image: "/company-4.png",
    company: "Zava",
  },
  {
    id: 15,
    jobTitle: "Food Chemist",
    category: "Management & Executive",
    jobtype: "Internship",
    qualification: "Diploma",
    experience: "fresher",
    gender: "Female",
    deadline: "10/05/2025",
    jobLocation: "On-site",
    salary: 19.8,
    location: "Uganda",
    applied: 39,
    isActive: false,
    image: "/company-4.png",
    company: "Tagopia",
  },
  {
    id: 16,
    jobTitle: "Computer Systems Analyst IV",
    category: "Marketing & Advertising",
    jobtype: "Full-time",
    qualification: "Doctorate",
    experience: "1-2",
    gender: "Female",
    deadline: "24/09/2024",
    jobLocation: "On-site",
    salary: 15.9,
    location: "France",
    applied: 3,
    isActive: false,
    image: "/company-2.png",
    company: "Gabtune",
  },
  {
    id: 17,
    jobTitle: "Financial Advisor",
    category: "Construction & Skilled Trades",
    jobtype: "Part-time",
    qualification: "Masters Degree",
    experience: ">6",
    gender: "Female",
    deadline: "23/03/2025",
    jobLocation: "On-site",
    salary: 13.1,
    location: "Armenia",
    applied: 48,
    isActive: false,
    image: "/company-1.png",
    company: "Camido",
  },
  {
    id: 18,
    jobTitle: "Community Outreach Specialist",
    category: "Finance & Accounting",
    jobtype: "Part-time",
    qualification: "Bachelors Degree",
    experience: "4-6",
    gender: "All",
    deadline: "15/04/2025",
    jobLocation: "Remote",
    salary: 14.6,
    location: "Brazil",
    applied: 73,
    isActive: false,
    image: "/company-3.png",
    company: "Thoughtmix",
  },
  {
    id: 19,
    jobTitle: "Senior Developer",
    category: "Finance & Accounting",
    jobtype: "Part-time",
    qualification: "Diploma",
    experience: "0-1",
    gender: "Female",
    deadline: "12/05/2025",
    jobLocation: "W-F-H",
    salary: 11.4,
    location: "Mongolia",
    applied: 11,
    isActive: true,
    image: "/company-4.png",
    company: "Jamia",
  },
  {
    id: 20,
    jobTitle: "Analog Circuit Design manager",
    category: "Sales",
    jobtype: "Full-time",
    qualification: "Certificate",
    experience: "fresher",
    gender: "Male",
    deadline: "09/12/2024",
    jobLocation: "W-F-H",
    salary: 36.4,
    location: "Russia",
    applied: 3,
    isActive: true,
    image: "/company-2.png",
    company: "Zoonder",
  },
  {
    id: 21,
    jobTitle: "VP Sales",
    category: "Healthcare & Medical",
    jobtype: "Full-time",
    qualification: "Bachelors Degree",
    experience: ">6",
    gender: "All",
    deadline: "11/02/2025",
    jobLocation: "On-site",
    salary: 17.8,
    location: "Norway",
    applied: 55,
    isActive: true,
    image: "/company-2.png",
    company: "Skipfire",
  },
  {
    id: 22,
    jobTitle: "Software Test Engineer II",
    category: "Finance & Accounting",
    jobtype: "Internship",
    qualification: "Diploma",
    experience: "4-6",
    gender: "Female",
    deadline: "02/05/2025",
    jobLocation: "On-site",
    salary: 29.1,
    location: "Colombia",
    applied: 1,
    isActive: true,
    image: "/company-1.png",
    company: "Browsetype",
  },
  {
    id: 23,
    jobTitle: "Budget/Accounting Analyst III",
    category: "Human Resources & Recruitment",
    jobtype: "Part-time",
    qualification: "Bachelors Degree",
    experience: "2-4",
    gender: "All",
    deadline: "31/05/2025",
    jobLocation: "Remote",
    salary: 20.4,
    location: "Russia",
    applied: 3,
    isActive: false,
    image: "/company-1.png",
    company: "Zoozzy",
  },
  {
    id: 24,
    jobTitle: "Biostatistician III",
    category: "Healthcare & Medical",
    jobtype: "Full-time",
    qualification: "Doctorate",
    experience: ">6",
    gender: "Female",
    deadline: "13/04/2025",
    jobLocation: "W-F-H",
    salary: 4.0,
    location: "Indonesia",
    applied: 3,
    isActive: true,
    image: "/company-1.png",
    company: "Skiba",
  },
  {
    id: 25,
    jobTitle: "Geologist IV",
    category: "Finance & Accounting",
    jobtype: "Part-time",
    qualification: "Bachelors Degree",
    experience: "2-4",
    gender: "All",
    deadline: "02/02/2025",
    jobLocation: "On-site",
    salary: 18.0,
    location: "Indonesia",
    applied: 96,
    isActive: true,
    image: "/company-2.png",
    company: "Gigaclub",
  },
  {
    id: 26,
    jobTitle: "Marketing Assistant",
    category: "Software Development & IT",
    jobtype: "Internship",
    qualification: "Masters Degree",
    experience: "4-6",
    gender: "Female",
    deadline: "12/05/2025",
    jobLocation: "On-site",
    salary: 3.1,
    location: "Thailand",
    applied: 32,
    isActive: false,
    image: "/company-4.png",
    company: "Skipfire",
  },
  {
    id: 27,
    jobTitle: "Marketing Manager",
    category: "Software Development & IT",
    jobtype: "Full-time",
    qualification: "Doctorate",
    experience: "2-4",
    gender: "All",
    deadline: "28/08/2024",
    jobLocation: "hybrid",
    salary: 19.7,
    location: "Indonesia",
    applied: 88,
    isActive: true,
    image: "/company-3.png",
    company: "Demizz",
  },
  {
    id: 28,
    jobTitle: "Staff Accountant II",
    category: "Software Development & IT",
    jobtype: "Part-time",
    qualification: "Doctorate",
    experience: "1-2",
    gender: "Female",
    deadline: "12/05/2025",
    jobLocation: "On-site",
    salary: 31.8,
    location: "Sweden",
    applied: 49,
    isActive: true,
    image: "/company-4.png",
    company: "Izio",
  },
  {
    id: 29,
    jobTitle: "Information Systems Manager",
    category: "Marketing & Advertising",
    jobtype: "Full-time",
    qualification: "Diploma",
    experience: "1-2",
    gender: "All",
    deadline: "03/05/2025",
    jobLocation: "W-F-H",
    salary: 32.9,
    location: "Greece",
    applied: 3,
    isActive: false,
    image: "/company-2.png",
    company: "Youbridge",
  },
  {
    id: 30,
    jobTitle: "Legal Assistant",
    category: "Marketing & Advertising",
    jobtype: "Part-time",
    qualification: "Masters Degree",
    experience: "2-4",
    gender: "Female",
    deadline: "21/02/2025",
    jobLocation: "On-site",
    salary: 31.1,
    location: "Poland",
    applied: 36,
    isActive: false,
    image: "/company-4.png",
    company: "Wikizz",
  },
];
