export const professionalSkills = [
  "Communication",
  "Teamwork",
  "Problem-Solving",
  "Time Management",
  "Critical Thinking",
  "Leadership",
  "Project Management",
  "Adaptability",
  "Technical Proficiency",
  "Customer Service",
  "Negotiation",
  "Creativity",
  "Data Analysis",
  "Research",
  "Financial Management",
  "Strategic Planning",
  "Marketing",
  "Sales",
  "Public Speaking",
  "Writing",
  "Networking",
  "Conflict Resolution",
  "Interpersonal Skills",
  "Attention to Detail",
  "Organizational Skills",
  "Multitasking",
  "Decision Making",
  "Mentoring",
  "Collaboration",
  "Emotional Intelligence",
  "Analytical Skills",
  "Coding/Programming",
  "Design",
  "Digital Marketing",
  "SEO",
  "Content Creation",
  "Customer Relationship Management (CRM)",
  "Budgeting",
  "Accounting",
  "Foreign Languages",
  "Event Planning",
  "Human Resources",
  "Recruitment",
  "Training and Development",
  "Quality Assurance",
  "Compliance",
  "Operations Management",
  "Supply Chain Management",
  "Risk Management",
  "Legal Knowledge",
  // Programming skills
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "TypeScript",
  "SQL",
  "NoSQL",
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Django",
  "Flask",
  "Spring Boot",
  "ASP.NET",
  "Ruby on Rails",
  "Laravel",
  "TensorFlow",
  "PyTorch",
  "Machine Learning",
  "Artificial Intelligence",
  "Blockchain",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "DevOps",
  "Git",
  "Agile Methodologies",
  "Scrum",
  "Mobile Development",
  "iOS Development",
  "Android Development",
  "Game Development",
  "Software Testing",
  "Unit Testing",
  "Integration Testing",
  "Continuous Integration/Continuous Deployment (CI/CD)",
];
